[versions]

# Jetpack Compose...
jetpackCompose = "1.5.3"

# Jetpack Compose (BOM)...
jetpackComposeBOM = "2023.10.00"

# Plugins...
androidGradlePlugin = "8.1.2"
activityCompose = "1.8.0"
kotlinPlugin = "1.9.10"
daggerHiltPlugin = "2.48.1"
kspPlugin = "1.9.10-1.0.13"

# Kotlin (Compose)...
coreKtx = "1.12.0"
lifecycleRuntimeKtx = "2.6.2"
appcompat = "1.6.1"
material = "1.10.0"
navigation-compose = "2.7.4"

# Testing...
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

# Dagger-Hilt...
hilt-android = "2.48.1"
hilt-work = "1.0.0"

# Room...
roomRuntime = "2.5.2"

[libraries]

# Jetpack Compose...
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "jetpackComposeBOM" }

# Kotlin (Jetpack Compose)...
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Navigation...
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }

# Dagger-Hilt...
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-work" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-work" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }

# Testing...
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
junit = { module = "junit:junit", version.ref = "junit" }

# Room...
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version = "2.7.4" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
com-google-dagger-hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "daggerHiltPlugin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }