[versions]
activityCompose = "1.8.0"
androidGradlePlugin = "8.1.2"
coreKtx = "1.12.0"
espressoCore = "3.5.1"
hiltAndroid = "2.48.1"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlinPlugin = "1.9.10"
daggerHiltPlugin = "2.48.1"
kspPlugin = "1.9.10-1.0.13"
lifecycleRuntimeKtx = "2.6.2"
roomRuntime = "2.5.2"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }
junit = { module = "junit:junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }


[plugins]
com-android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
com-google-dagger-hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "daggerHiltPlugin" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspPlugin" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }