[versions]

# Plugins
gradleVersion = "8.2.1"
kotlinAndroidVersion = "1.9.21"
kspVersion = "1.9.21-1.0.15"
daggerHiltPluginVersion = "2.48.1"
googleServicesVersion = "4.4.0"
firebaseCrashlyticsVersion = "2.9.9"
secretsGradlePlugin = "2.0.1"
firebasePerformanceVersion = "1.4.2"
appSweepGradlePluginVersion = "latest.release"
kotlinSerializationPluginVersion = "1.9.21"
composeMultiplatformVersion = "1.5.11"

# Kotlin Compiler...
kotlinCompilerVersion = "1.5.6"

# Activity Compose...
activityComposeVersion = "1.8.2"

# Firebase BOM...
firebaseBOMVersion = "32.7.0"

# Glide...
glideVersion = "1.0.0-beta01"

# Splash...
splashVersion = "1.0.1"

# Room...
roomVersion = "2.6.1"

# Swipe To Refresh (Accompanist)...
swipeToRefreshVersion = "0.27.0"

# LeakCanary...
leakCanaryVersion = "2.12"

# Timber...
timberVersion = "5.0.1"

# CameraX...
cameraX = "1.4.0-alpha03"

# Kotlin Serialization...
kotlinSerializationLibrary = "1.6.0"

# Emoji Picker...
emojiPickerVersion = "1.4.0"

# GMS Play Services (Auth)...
gmsPlayServicesVersion = "20.7.0"

# Voyager...
voyagerVersion = "1.0.0"

# Koin Version...
koinVersion = "3.5.3"

# Kamel...
kamelVersion = "0.9.1"

[libraries]

# Activity Compose...
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }

# Firebase...
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBOMVersion" }
firebase-cloud-firestore = { group = "com.google.firebase", name = "firebase-firestore" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-cloud-messaging = { group = "com.google.firebase", name = "firebase-messaging" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf" }
firebase-authentication = { group = "com.google.firebase", name = "firebase-auth" }

# Play Services...
gms-play-services = { module = "com.google.android.gms:play-services-auth", version.ref = "gmsPlayServicesVersion" }

# Glide...
com-github-bumptech-glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glideVersion" }

# Splash...
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashVersion" }

# Room...
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }

# Swipe To Refresh (Accompanist)...
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "swipeToRefreshVersion" }

# LeakCanary...
leakCanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanaryVersion" }

# Timber...
timber = { module = "com.jakewharton.timber:timber", version.ref = "timberVersion" }

# CameraX...
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraX" }
kotlin-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinSerializationLibrary" }

# Emoji Picker...
emoji-picker = { module = "androidx.emoji2:emoji2-emojipicker", version.ref = "emojiPickerVersion" }

# Voyager...
voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyagerVersion" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyagerVersion" }

# Koin...
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinVersion" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinVersion" }
koin-multiplatform = { module = "io.insert-koin:koin-core", version.ref = "koinVersion" }

# Kamel...
kamel = { module = "media.kamel:kamel-image", version.ref = "kamelVersion" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "gradleVersion" }
com-android-library = { id = "com.android.library", version.ref = "gradleVersion" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidVersion" }
org-jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlinAndroidVersion" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleServicesVersion" }
com-google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsVersion" }
com-google-android-libraries-mapsplatform-secrets-gradle-plugin = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secretsGradlePlugin" }
com-google-firebase-performance = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerformanceVersion" }
com-guardsquare-appsweep = { id = "com.guardsquare.appsweep", version.ref = "appSweepGradlePluginVersion" }
plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPluginVersion" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatformVersion" }